service: free-retro

plugins:
  - serverless-finch
  - serverless-plugin-log-retention
  - serverless-single-page-app-plugin

custom:
  logRetentionInDays: 30
  client:
    bucketName: free-retro
    distributionFolder: dist/app
    indexDocument: index.html
    errorDocument: index.html

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  websocketsApiName: free-retro-api
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Free retro sync backend
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "Fn::GetAtt": [freeRetroTable, Arn]

package:
  exclude:
    - ./**
  individually: true

functions:
  connectionHandler:
    handler: dist/lambda/handler.lambdaHandler
    package:
      patterns:
        - "dist/lambda/handler.js"
        - "dist/lambda/handler.js.map"
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

resources:
  Resources:
    freeRetroTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: free-retro-sessions-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
          - AttributeName: connectionId
            KeyType: RANGE
    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${self:custom.client.bucketName}.s3.amazonaws.com
              Id: WebApp
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          Enabled: "true"
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: WebApp
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: "true"

  Outputs:
    WebAppCloudFrontDistributionOutput:
      Value:
        "Fn::GetAtt": [WebAppCloudFrontDistribution, DomainName]
